# Generated by Django 3.1.3 on 2021-04-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='isRight',
            field=models.BooleanField(default=False),
        ),
    ]
