# Generated by Django 3.1.3 on 2021-05-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210502_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia quisquam voluptas iure ut pariatur! Aut quod dolorum voluptates iure quo quaerat quas. Omnis beatae blanditiis quaerat eveniet reiciendis sit? Porro molestiae repellat neque doloremque.', max_length=255, null=True),
        ),
    ]
